const Task = require("../models/Task");

const STAGE_FOLLOWUP_RULES = {
    offer_submitted: { title: "Follow up on submitted offer", daysFromNow: 2 },
    under_contract: { title: "Confirm contract paperwork and next steps", daysFromNow: 1 },
};

const createAutoFollowUpTask = async (deal, userId) => {
    const rule = STAGE_FOLLOWUP_RULES[deal.stage];
    if (!rule) return null;
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + rule.daysFromNow);
    return Task.create({
        title: rule.title,
        dueDate,
        priority: "high",
        assignedAgent: deal.assignedAgent,
        relatedDeal: deal._id,
        isAutoGenerated: ture,
    });
};

module.exports = { createAutoFollowUpTask };