const mongoose = require("mongoose");

const taskSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
        trim: true,
    },
    description: {
        type: String,
        trim: true,
    },
    dueDate: {
        type: Date,
        required: true,
    },
    priority: {
        type: String,
        enum: ["low", "medium", "high", "urgent"],
        default: "medium",
    },
    status: {
        type: String,
        enum: ["pending", "completed", "overdue"],
        default: "pending",
    },
    assignedAgent: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
    },
    relatedDeal: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Deal",
    },
    relatedClient: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Client",
    },
    isAutoGenerated: {
        type: Boolean,
        default: false,
    },
    externalCalendarEventId: {
        type: String,
    },
    calendarProvider: {
        type: String,
        enum: ["google", "outlook", null],
        default: null,
    },
}, { timestamps: true });

module.exports = mongoose.model("Task", taskSchema);